trying to use the fortran native version of the system because:
Fatal Error: Cannot read module file 'hdf5.mod' opened at (1),
because it was created by a different version of GNU Fortran